### PR TITLE
update resource files with latest enums and translations

### PR DESCRIPTION
**Pull request by michaelgwelch**

### CODE REVIEW

**Comment by michaelgwelch** [comment]
Hmm, the diffs are too large to inspect which I didn't expect. Something must have gone wrong. Will check diffs locally and re-share

**Comment by michaelgwelch** [comment]
@Federico-Artioli this is getting closer to being done. But what I think I'd like to do is

1. Create a job internally that publishes a new nuget packages whenever translations change.
2. This nuget package would have the resource files embedded.
3. We could publish these publicly when a release happens or whenever a patch is needed
4. This library itself would remove the resource files and just take a dependency on the nuget package.
thoughts?

**Review by Federico-Artioli — APPROVED** [review]
I think the related .resources file have to be generated. 
I will merge this PR and then I will commit the corresponding files.

**Comment by michaelgwelch** [comment]
Oh, I didn't expect you to merge this. It was still in draft. Just a note that I have a "better" idea for the future.

There are a small number of conflicts in each resource file. Symbols that only differ in casing are considered duplicates and we have a handful. 

I've got a project that consumes the same "resource" files that the MUI client uses. I'd like to publish that and you can then consider using that in your project.

**Pull request merged**
